type/docs:
- all:
  - changed-files:
    - any-glob-to-any-file: ['docs/*', 'operator/docs/*', '**/README.md']
    - all-globs-to-all-files: ['!vendor/**/README.md']
sig/operator:
- 'operator/**/*'
kind/feature:
- 'operator/docs/enhancements/*'
area/helm:
- 'production/helm/**/*'
